In [18]:
pip install pandas

Requirement already satisfied: pandas in e:\imagens\trabalho-multidisciplinar-main\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in e:\imagens\trabalho-multidisciplinar-main\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\imagens\trabalho-multidisciplinar-main\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\imagens\trabalho-multidisciplinar-main\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in e:\imagens\trabalho-multidisciplinar-main\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import pandas as pd

In [26]:
df = pd.read_csv("data.csv")

print("Linhas e colunas:", df.shape)
df.head()

Linhas e colunas: (501, 63)

,Gender,Relationship Status,Age,Academic Status,Do you work as well as Study?(পড়াশোনার পাশাপাশি চাকরি করেন?),Residential Area (আবাসিক এলাকা),Social Economic Status (আর্থ-সামাজিক অবস্থা),Do you feel any financial pressure?(আপনি কি কোনো আর্থিক চাপ অনুভব করছেন?),Does the participant have any debts?(অংশগ্রহণকারী কি কোন ঋণ আছে?),Are you satisfied with your current living environment? (আপনি কি আপনার বর্তমান বসবাসের পরিবেশে সন্তুষ্ট?),...,How often do you feel isolated from others?(আপনি কতবার অন্যদের থেকে বিচ্ছিন্ন বোধ করেন?),How frequently do you feel there’s no one you can rely on for support?(আপনি কত ঘন ঘন মনে করেন যে সমর্থনের জন্য আপনি নির্ভর করতে পারেন এমন কেউ নেই?),How frequently do you experience feelings of loneliness? (আপনি কত ঘন ঘন একাকীত্বের অনুভূতি অনুভব করেন?),How frequently do you feel aligned with the emotions or thoughts of the people around you? (আপনি কত ঘন ঘন আপনার চারপাশের লোকেদের আবেগ বা চিন্তার সাথে একত্রিত বোধ করেন?),How frequently do you perceive that people are around you but not genuinely present with you? (আপনি কত ঘন ঘন বুঝতে পারেন যে লোকেরা আপনার চারপাশে আছে কিন্তু সত্যিকারের আপনার সাথে উপস্থিত নয়?),To what extent do you experience your relationships with others as being unimportant?(অন্যদের সাথে আপনার সম্পর্ককে গুরুত্বহীন বলে আপনি কতটা অনুভব করেন?),Depression Level (BDI-II) (20 items),Depression Level (PHQ-9 items),Depression Level (CES-D) (20 items),Loneliness Level (UCLA-8 items)
0,Male,Single,25.0,4 Year,No,Hall,Middle,Yes,No,Yes,...,Never,Never,Never,Never,Never,Never,Moderate Depression,Moderate Depression,Mild Depression,Low degree of loneliness
1,Female,Single,23.0,3 Year,No,Hall,Middle,No,No,Yes,...,Rarely,Never,Sometimes,Often,Sometimes,Rarely,Moderate Depression,Mild Depression,Mild Depression,Moderate degree of loneliness
2,Female,Single,22.0,3 Year,No,Hall,Middle,Yes,No,No,...,Often,Never,Often,Often,Often,Often,Severe Depression,Severe Depression,Severe Depression,Moderately high degree of loneliness
3,Male,Single,21.0,3 Year,No,With family,Upper-Middle,No,No,No,...,Rarely,Never,Rarely,Sometimes,Rarely,Rarely,Minimal Depression,Minimal Depression,Minimal or no Depressive,Low degree of loneliness
4,Male,Single,23.0,3 Year,No,Hall,Middle,Yes,Yes,Yes,...,Often,Sometimes,Often,Never,Often,Often,Severe Depression,Severe Depression,Severe Depression,Moderately high degree of loneliness

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                          --------------  -----
 0   Gender                                                                                                                                                                                                                                          500 non-null    str
 1   Relationship Status                                                                                                                                                                                                                             500 non-null    str
 2   Age                                                                                                                                                                                                                                             500 non-null    float64
 3   Academic Status                                                                                                                                                                                                                                 500 non-null    str
 4   Do you work as well as Study?(পড়াশোনার পাশাপাশি চাকরি করেন?)                                                                                                                                                                                   500 non-null    str
 5   Residential Area (আবাসিক এলাকা)                                                                                                                                                                                                                 500 non-null    str
 6   Social Economic Status (আর্থ-সামাজিক অবস্থা)                                                                                                                                                                                                    500 non-null    str
 7   Do you feel any financial pressure?(আপনি কি কোনো আর্থিক চাপ অনুভব করছেন?)                                                                                                                                                                       500 non-null    str
 8   Does the participant have any debts?(অংশগ্রহণকারী কি কোন ঋণ আছে?)                                                                                                                                                                               500 non-null    str
 9   Are you satisfied with your current living environment? (আপনি কি আপনার বর্তমান বসবাসের পরিবেশে সন্তুষ্ট?)                                                                                                                                       500 non-null    str
 10  Have you recently lost someone close to you? (আপনি সম্প্রতি আপনার কাছের কাউকে হারিয়েছেন কি না )                                                                                                                                                500 non-null    str
 11  You are actively engaging as a participant in physical exertion.(আপনি সক্রিয়ভাবে শারীরিক পরিশ্রমে অংশগ্রহণকারী হিসাবে জড়িত।)                                                                                                                  500 non-null    str
 12  Are you afflicted by any significant ailments?(আপনি কি কোনও গুরুতর অসুখে ভুগছেন?")                                                                                                                                                              500 non-null    str
 13  Are you currently on any prescribed medication?(আপনি কি বর্তমানে কোনও ওষুধ সেবন করছেন?)                                                                                                                                                         500 non-null    str
 14  Are you accustomed to smoking?(আপনি কি ধূমপানে অভ্যস্ত?)                                                                                                                                                                                        500 non-null    str
 15  Do you consume alcoholic beverages?(আপনি কি অ্যালকোহলযুক্ত পানীয় গ্রহণ করেন?)                                                                                                                                                                  500 non-null    str
 16  What is your average nightly sleep duration in hours?(আপনার রাতের ঘুমের গড় সময়কাল কত ঘন্টার মধ্যে?)                                                                                                                                           500 non-null    str
 17  Average hours that the participant spends in social network (in a day)(অংশগ্রহণকারী সামাজিক নেটওয়ার্কে ব্যয় করে এমন গড় ঘন্টা (এক দিনে))                                                                                                      500 non-null    str
 18  Do you have current workload or academic demands?(আপনার কি বর্তমান কাজের চাপ বা একাডেমিক চাহিদা রয়েছে?)                                                                                                                                        500 non-null    str
 19  Presently, I feel melancholic. (ইদানিং আমি মনমরা থাকি। )                                                                                                                                                                                        500 non-null    str
 20  My future appears shrouded in darkness. (আমার ভবিষ্যৎ অন্ধকার ম‌নে হয়।)                                                                                                                                                                         500 non-null    str
 21  At present, I perceive myself as utterly unsuccessful as a human being. (বর্তমানে আমি অনুভব করি যে মানুষ হিসেবে আমি সম্পূর্ণ ব্যর্থ।)                                                                                                           500 non-null    str
 22  I find no interest in anything whatsoever. (আমি কোন কিছুতেই আগ্রহ পাই না। )                                                                                                                                                                     500 non-null    str
 23  Life feels devoid of meaning.(জীবনটা অর্থহীন।)                                                                                                                                                                                                  500 non-null    str
 24  I feel like, All has come to an end for me. (আমার সব শেষ হয়ে গেছে, এমনটা ম‌নে হয়।)                                                                                                                                                              500 non-null    str
 25  I feel remarkably insignificant within myself. (নিজেকে খুব ছোট মনে হয় আমার।)                                                                                                                                                                    500 non-null    str
 26  Everything seems to have eroded my self-confidence.(সব কিছুতে আমার আত্মবিশ্বাস কমে গেছে।)                                                                                                                                                       500 non-null    str
 27  Have you recently entertained any suicidal or self-harming thoughts?(আপনি ইদানীং কোনো আত্মঘাতী বা আত্ম-ক্ষতির চিন্তাভাবনা উপভোগ করেছেন কি না ?)                                                                                                 500 non-null    str
 28  I often get tears. (প্রায়ই আমার কান্না পায়।)                                                                                                                                                                                                    500 non-null    str
 29  I'm easily agitated. (আমি সহজেই উত্তেজিত। )                                                                                                                                                                                                     500 non-null    str
 30  I can't participate in social activities like I used to.(সামাজিক কাজকর্মে আগের মতো অংশগ্রহন করতে পারি না।)                                                                                                                                      500 non-null    str
 31  I suffer from indecisiveness. (আমি সিদ্ধান্তহীনতায় ভুগি।)                                                                                                                                                                                       500 non-null    str
 32  I find myself devoid of joy anywhere. (আমি কোথাও আনন্দ ফুর্তি পাই না।)                                                                                                                                                                          500 non-null    str
 33  How often do you feel weak and fatigued easily?(আপনি কত ঘন ঘন দুর্বল এবং সহজেই ক্লান্ত বোধ করেন?)                                                                                                                                               500 non-null    str
 34  Insomnia (difficulty falling asleep, broken sleep, unsatisfying sleep, fatigue on waking, dreams, nightmares, and night terrors.)
অনিদ্রা (ঘুমিয়ে পড়তে অসুবিধা, ভাঙা ঘুম, অতৃপ্ত ঘুম, জেগে ওঠার ক্লান্তি, স্বপ্ন, দুঃস্বপ্ন এবং রাতের আতঙ্ক।  500 non-null    str
 35  My temper is irritable. (আমার মেজাজ খিঁটখিঁটে হয়ে গেছে। )                                                                                                                                                                                       500 non-null    str
 36  My appetite has diminished. (আমার ক্ষুধা কমে গেছে।)                                                                                                                                                                                             500 non-null    str
 37  Concentrating on one topic is quite taxing for me.(একটি বিষয়ে মনোনিবেশ করা আমার জন্য বেশ করকর।)                                                                                                                                                500 non-null    str
 38  I feel weak and fatigued easily.(আমি সহজেই দুর্বল এবং ক্লান্ত বোধ করি।)                                                                                                                                                                         500 non-null    str
 39  My appetite has increased. (আমার ক্ষুধা বেড়ে গেছে।)                                                                                                                                                                                             500 non-null    str
 40  Lately, I find it challenging to focus on many things. (আমি আজকাল অনেক কিছুতে মনোযোগ দিতে পারি না।)                                                                                                                                             500 non-null    str
 41  I find it difficult to speak in my social environment. (আমার সামাজিক পরিবেশে কথা বলতে অসুবিধা হয়।)                                                                                                                                              500 non-null    str
 42   I'm plagued by a sense of unrest. (আমি অস্থিরতার অনুভূতিতে জর্জরিত।)/(আমার অশান্তি লাগে। )                                                                                                                                                     500 non-null    str
 43  I reckon life has become exceedingly arduous presently. (আমি মনে করি যে,জীনবটা বর্তমানে খুব বেশী কষ্টকর।)                                                                                                                                       500 non-null    str
 44  I'm afraid something very bad will happen.(আমার খুব খারাপ কিছু ঘটবে বলে আশংকা হয়।)                                                                                                                                                              500 non-null    str
 45  Whether the participant has recently felt abused (physically, emotionally, Sexual Harassment) or Not (অংশগ্রহণকারী সম্প্রতি নির্যাতিত (শারীরিক, মানসিক, যৌন হয়রানি) অনুভব করেছেন কি না)                                                        500 non-null    str
 46  I feel that people show me compassion. (আমার মনে হয় মানুষ আমাকে করুণা করে।)                                                                                                                                                                     500 non-null    str
 47  I find myself absence of pleasure everywhere.  (আমি সব জায়গায় নিজেকে আনন্দের অনুপস্থিতি খুঁজে পাই।)                                                                                                                                           500 non-null    str
 48  Presently, I'm feeling down.  (বর্তমানে, আমি খারাপ বোধ করছি।)                                                                                                                                                                                   500 non-null    str
 49  I feel that people are kind toward me. (আমি অনুভব করি যে লোকেরা আমার প্রতি সদয়।)                                                                                                                                                               500 non-null    str
 50  I find myself unable to perform educational and professional duties as before. (শিক্ষা ও পেশাগত কাজকর্ম আগের মতো করতে পারি না।)                                                                                                                 500 non-null    str
 51  How often do you feel like you don't have anyone to share your feelings with? (আপনি কতবার মনে করেন যে আপনার সাথে আপনার অনুভূতি ভাগ করার মতো কেউ নেই?)                                                                                           500 non-null    str
 52  How much do you feel left out in social situations? (সামাজিক পরিস্থিতিতে আপনি কতটা বাকী বোধ করেন?)                                                                                                                                              500 non-null    str
 53  How often do you feel isolated from others?(আপনি কতবার অন্যদের থেকে বিচ্ছিন্ন বোধ করেন?)                                                                                                                                                        500 non-null    str
 54  How frequently do you feel there’s no one you can rely on for support?(আপনি কত ঘন ঘন মনে করেন যে সমর্থনের জন্য আপনি নির্ভর করতে পারেন এমন কেউ নেই?)                                                                                             500 non-null    str
 55  How frequently do you experience feelings of loneliness? (আপনি কত ঘন ঘন একাকীত্বের অনুভূতি অনুভব করেন?)                                                                                                                                         500 non-null    str
 56  How frequently do you feel aligned with the emotions or thoughts of the people around you? (আপনি কত ঘন ঘন আপনার চারপাশের লোকেদের আবেগ বা চিন্তার সাথে একত্রিত বোধ করেন?)                                                                        500 non-null    str
 57  How frequently do you perceive that people are around you but not genuinely present with you? (আপনি কত ঘন ঘন বুঝতে পারেন যে লোকেরা আপনার চারপাশে আছে কিন্তু সত্যিকারের আপনার সাথে উপস্থিত নয়?)                                                 500 non-null    str
 58  To what extent do you experience your relationships with others as being unimportant?(অন্যদের সাথে আপনার সম্পর্ককে গুরুত্বহীন বলে আপনি কতটা অনুভব করেন?)                                                                                        500 non-null    str
 59  Depression Level (BDI-II) (20 items)                                                                                                                                                                                                            500 non-null    str
 60  Depression Level (PHQ-9 items)                                                                                                                                                                                                                  500 non-null    str
 61  Depression Level (CES-D) (20 items)                                                                                                                                                                                                             500 non-null    str
 62  Loneliness Level (UCLA-8 items)                                                                                                                                                                                                                 500 non-null    str
dtypes: float64(1), str(62)
memory usage: 246.7 KB

In [27]:
df["Age"].describe()

count    500.000000
mean      22.282000
std        1.646785
min       18.000000
25%       21.000000
50%       22.000000
75%       23.000000
max       28.000000
Name: Age, dtype: float64

In [23]:
df.isnull().sum()

Gender                                                                                                                                                      1
Relationship Status                                                                                                                                         1
Age                                                                                                                                                         1
Academic Status                                                                                                                                             1
Do you work as well as Study?(পড়াশোনার পাশাপাশি চাকরি করেন?)                                                                                               1
                                                                                                                                                           ..
To what extent do you experience your relationships with others as being unimportant?(অন্যদের সাথে আপনার সম্পর্ককে গুরুত্বহীন বলে আপনি কতটা অনুভব করেন?)    1
Depression Level (BDI-II) (20 items)                                                                                                                        1
Depression Level (PHQ-9 items)                                                                                                                              1
Depression Level (CES-D) (20 items)                                                                                                                         1
Loneliness Level (UCLA-8 items)                                                                                                                             1
Length: 63, dtype: int64

# Observou-se que existe aproximadamente 1 valor ausente em praticamente todas as colunas do dataset.

In [29]:
df["Gender"].value_counts()

Gender
Male      357
Female    143
Name: count, dtype: int64

In [30]:
df["Depression Level (BDI-II) (20 items)"].value_counts()

Depression Level (BDI-II) (20 items)
Minimal Depression     165
Severe Depression      142
Moderate Depression    112
Mild Depression         81
Name: count, dtype: int64

# Pré-processamento (Curadoria)

In [31]:
print("Antes:", df.shape)

df = df.drop_duplicates()

print("Depois:", df.shape)

Antes: (501, 63)
Depois: (501, 63)

In [32]:
df = df.dropna()

In [33]:
df.isnull().sum().sum()

np.int64(0)

In [34]:
df.dtypes

Gender                                                                                                                                                          str
Relationship Status                                                                                                                                             str
Age                                                                                                                                                         float64
Academic Status                                                                                                                                                 str
Do you work as well as Study?(পড়াশোনার পাশাপাশি চাকরি করেন?)                                                                                                   str
                                                                                                                                                             ...
To what extent do you experience your relationships with others as being unimportant?(অন্যদের সাথে আপনার সম্পর্ককে গুরুত্বহীন বলে আপনি কতটা অনুভব করেন?)        str
Depression Level (BDI-II) (20 items)                                                                                                                            str
Depression Level (PHQ-9 items)                                                                                                                                  str
Depression Level (CES-D) (20 items)                                                                                                                             str
Loneliness Level (UCLA-8 items)                                                                                                                                 str
Length: 63, dtype: object

In [35]:
print(df.shape)

df.head()

(500, 63)

,Gender,Relationship Status,Age,Academic Status,Do you work as well as Study?(পড়াশোনার পাশাপাশি চাকরি করেন?),Residential Area (আবাসিক এলাকা),Social Economic Status (আর্থ-সামাজিক অবস্থা),Do you feel any financial pressure?(আপনি কি কোনো আর্থিক চাপ অনুভব করছেন?),Does the participant have any debts?(অংশগ্রহণকারী কি কোন ঋণ আছে?),Are you satisfied with your current living environment? (আপনি কি আপনার বর্তমান বসবাসের পরিবেশে সন্তুষ্ট?),...,How often do you feel isolated from others?(আপনি কতবার অন্যদের থেকে বিচ্ছিন্ন বোধ করেন?),How frequently do you feel there’s no one you can rely on for support?(আপনি কত ঘন ঘন মনে করেন যে সমর্থনের জন্য আপনি নির্ভর করতে পারেন এমন কেউ নেই?),How frequently do you experience feelings of loneliness? (আপনি কত ঘন ঘন একাকীত্বের অনুভূতি অনুভব করেন?),How frequently do you feel aligned with the emotions or thoughts of the people around you? (আপনি কত ঘন ঘন আপনার চারপাশের লোকেদের আবেগ বা চিন্তার সাথে একত্রিত বোধ করেন?),How frequently do you perceive that people are around you but not genuinely present with you? (আপনি কত ঘন ঘন বুঝতে পারেন যে লোকেরা আপনার চারপাশে আছে কিন্তু সত্যিকারের আপনার সাথে উপস্থিত নয়?),To what extent do you experience your relationships with others as being unimportant?(অন্যদের সাথে আপনার সম্পর্ককে গুরুত্বহীন বলে আপনি কতটা অনুভব করেন?),Depression Level (BDI-II) (20 items),Depression Level (PHQ-9 items),Depression Level (CES-D) (20 items),Loneliness Level (UCLA-8 items)
0,Male,Single,25.0,4 Year,No,Hall,Middle,Yes,No,Yes,...,Never,Never,Never,Never,Never,Never,Moderate Depression,Moderate Depression,Mild Depression,Low degree of loneliness
1,Female,Single,23.0,3 Year,No,Hall,Middle,No,No,Yes,...,Rarely,Never,Sometimes,Often,Sometimes,Rarely,Moderate Depression,Mild Depression,Mild Depression,Moderate degree of loneliness
2,Female,Single,22.0,3 Year,No,Hall,Middle,Yes,No,No,...,Often,Never,Often,Often,Often,Often,Severe Depression,Severe Depression,Severe Depression,Moderately high degree of loneliness
3,Male,Single,21.0,3 Year,No,With family,Upper-Middle,No,No,No,...,Rarely,Never,Rarely,Sometimes,Rarely,Rarely,Minimal Depression,Minimal Depression,Minimal or no Depressive,Low degree of loneliness
4,Male,Single,23.0,3 Year,No,Hall,Middle,Yes,Yes,Yes,...,Often,Sometimes,Often,Never,Often,Often,Severe Depression,Severe Depression,Severe Depression,Moderately high degree of loneliness

# Conclusão

Foram analisados dados relacionados à depressão, solidão e características sociais dos participantes.

Durante o pré-processamento foram realizadas:

- Verificação da estrutura dos dados;
- Identificação de valores ausentes;
- Remoção de registros duplicados;
- Tratamento dos valores nulos.

Após a limpeza, o conjunto de dados ficou preparado para análises estatísticas mais avançadas e possíveis aplicações de aprendizado de máquina.